#:schema node_modules/wrangler/config-schema.json
name = "next-cloudflare"
main = ".open-next/worker.js"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

# Minification helps to keep the Worker bundle size down and improve start up time.
minify = true

# Use the new Workers + Assets to host the static frontend files
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "POSTS"
id = "ddee157e148f41d4a19044788f4d7644"

[[d1_databases]]
binding = "DB"
database_name = "goose-goss-db"
database_id = "19940f18-e6c8-4c53-926c-0fb79118f598"
